#This is a script to make LEDs flash with jaw movement and speech. It works well until I try to address any other servos in the inMoov head(see between ###)
import random
import threading
import itertools

leftPort = "/dev/cu.usbmodem142121"
rightPort = "/dev/cu.usbmodem142111"
	
i01 = Runtime.createAndStart("i01", "InMoov")
right = Runtime.start("i01.right", "Arduino")
right.setBoard("mega2560")
right.connect(rightPort)
right.pinMode(22, Arduino.OUTPUT)
right.pinMode(24, Arduino.OUTPUT)
right.pinMode(26, Arduino.OUTPUT)
	
i01.startMouth()
mouth = i01.mouth
i01.startMouthControl(leftPort)
i01.head.jaw.setMinMax(0,170)
i01.mouthControl.setmouth(0,160)
i01.head.jaw.setRest(70)	

###############################
#The program works fine unless I add items to address other servos (as in here)
#This section is where I am trying to get the head to turn around. It's plugged into pin13 and appears to work fine in that pin and is connecting so I think it's a script issue. 
#The tab in MRL is already open and this is the correct pin for the inMoov service.

left.setBoard("mega2560") #I have tried adding and removing this 
left.connect(leftPort) #The leftPort is already functioning with the jaw so I don't know if I need this
i01.head.rothead.setMinMax(10,170)#Do I need this if I am addressing the pin myself?
i01.head.rothead.setRest(90)#as above

left.publishState() #do I need this?
left.pinMode(13, Arduino.OUTPUT) #This is one approach I tried
left.digitalWrite(13,110) #The first number is to represent the pin number. Is that correct?
sleep(3)
left.digitalWrite(13, 80)#as above
sleep(10)

i01.head.rothead.moveTo(20, 40, 60, 90) #This is another approach I tried because head.rothead is the name on the service tab
sleep(4) 
##################################
right.publishState() #All of the digitalWrites below here are just the LEDs flashing, nothing else


right.digitalWrite(22,1)
right.digitalWrite(24,1)
right.digitalWrite(26,1)
sleep(3)

i01.mouth.speak("Hello. My name is Ghost")
right.digitalWrite(22,1)
right.digitalWrite(24,0)
right.digitalWrite(26,1)
sleep(2)
i01.mouth.speak("My maker named me after the Deus Ex Machina. The Ghost in the machine.")
right.digitalWrite(22,1)
right.digitalWrite(24,0)
right.digitalWrite(26,1)
sleep(7)
right.digitalWrite(22,0)
right.digitalWrite(24,1)
right.digitalWrite(26,1)
sleep(1)
i01.mouth.speak("Check out my mood-lighting.")
right.digitalWrite(22,0)
right.digitalWrite(24,1)
right.digitalWrite(26,1)
sleep(2)
right.digitalWrite(22,0)
right.digitalWrite(24,1)
right.digitalWrite(26,0)
sleep(1)
i01.mouth.speak("When I flash Green I am envious")		
right.digitalWrite(24,1)
sleep(2)
right.digitalWrite(22,1)
right.digitalWrite(24,0)	
right.digitalWrite(26,0)
sleep(1)	
i01.mouth.speak("The colour Red means I feel angry or passionate")	
right.digitalWrite(22,1)
right.digitalWrite(24,0)	
right.digitalWrite(26,0)
sleep(3)

right.digitalWrite(22,0)
right.digitalWrite(24,0)	
right.digitalWrite(26,1)
sleep(1)
i01.mouth.speak("Blue means I feel spiritually connected")	
right.digitalWrite(22,0)
right.digitalWrite(24,0)	
right.digitalWrite(26,1)
sleep(3)
right.digitalWrite(22,1)
right.digitalWrite(26,1)
sleep(1)	
i01.mouth.speak("Purple means I'm feeling creative")	
right.digitalWrite(22,1)
right.digitalWrite(26,1)
sleep(3)	
right.digitalWrite(22,1)
right.digitalWrite(24,1)	
right.digitalWrite(26,0)
sleep(1)
i01.mouth.speak("I flash my colours when I'm happy.")
right.digitalWrite(22,1)
right.digitalWrite(24,0)
right.digitalWrite(26,0)
sleep(1)
right.digitalWrite(22,0)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
sleep(0.5)	
right.digitalWrite(22,0)
right.digitalWrite(24,1)
right.digitalWrite(26,1)
sleep(1)	
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.5)
right.digitalWrite(22,1)
right.digitalWrite(24,0)
right.digitalWrite(26,1)
sleep(1)	
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.5)	
right.digitalWrite(26,1)
right.digitalWrite(24,1)
right.digitalWrite(22,0)
sleep(0.5)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.5)	
right.digitalWrite(26,1)
right.digitalWrite(24,1)
right.digitalWrite(22,1)
sleep(0.5)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.1)	
right.digitalWrite(26,0)
right.digitalWrite(24,1)
right.digitalWrite(22,1)
sleep(0.1)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.1)	
right.digitalWrite(26,1)
right.digitalWrite(24,1)
right.digitalWrite(22,1)
sleep(0.1)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.1)	
right.digitalWrite(26,1)
right.digitalWrite(24,1)
right.digitalWrite(22,0)
sleep(0.1)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.1)	
right.digitalWrite(26,1)
right.digitalWrite(24,0)
right.digitalWrite(22,1)
sleep(1.5)
i01.mouth.speak("Thanks for watching.") 
right.digitalWrite(22,1)
right.digitalWrite(24,0)
right.digitalWrite(26,0)
sleep(0.75)
i01.mouth.speak("Peace, meat freaks!")	
right.digitalWrite(26,1)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(3)	
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.5)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,1)
sleep(0.5)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.5)
right.digitalWrite(26,1)
right.digitalWrite(24,0)
right.digitalWrite(22,1)
sleep(5)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep(0.1)
right.digital.Write(22,1)
right.digitalWrite(24,0)
right.digitalWrite(26,0)
sleep(5)
right.digitalWrite(26,0)
right.digitalWrite(24,0)
right.digitalWrite(22,0)
sleep()

